# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-15 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.IntegerField()),
                ('step_name', models.CharField(max_length=50)),
                ('step_descri', models.CharField(max_length=200)),
                ('duration', models.IntegerField(blank=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.Roadmap')),
            ],
        ),
    ]
