# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-15 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.Step')),
            ],
        ),
    ]
