# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-15 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0003_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='roadmap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='roadmap.Roadmap'),
            preserve_default=False,
        ),
    ]
