# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-15 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0005_auto_20180415_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='r_descri',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
