# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-15 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='classroom',
            new_name='classrooms',
        ),
    ]
