# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-15 19:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_auto_20180415_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='lectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_name', models.CharField(max_length=100)),
                ('class_url', models.URLField()),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('trans_script', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='vote_classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='classrooms',
            name='class_room_name',
        ),
        migrations.RemoveField(
            model_name='classrooms',
            name='class_url',
        ),
        migrations.RemoveField(
            model_name='classrooms',
            name='is_live',
        ),
        migrations.AddField(
            model_name='classrooms',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classrooms',
            name='downvote_cnt',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classrooms',
            name='upvote_cnt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippets',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote_classroom',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.classrooms'),
        ),
        migrations.AddField(
            model_name='vote_classroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lectures',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.classrooms'),
        ),
    ]
