# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-15 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180415_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectures',
            old_name='class_url',
            new_name='lecture_url',
        ),
    ]
