# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-15 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20180415_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrooms',
            name='class_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
