# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-15 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_classrooms_class_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippets',
            old_name='code',
            new_name='c_code',
        ),
        migrations.AddField(
            model_name='snippets',
            name='cpp_code',
            field=models.TextField(default='#include <iostream>'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippets',
            name='java_code',
            field=models.TextField(default='class Solution {'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippets',
            name='py3c_code',
            field=models.TextField(default='print ("python 3")'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippets',
            name='py_code',
            field=models.TextField(default='print ("python2")'),
            preserve_default=False,
        ),
    ]
