# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-15 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_snippets_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippets',
            old_name='py3c_code',
            new_name='py3_code',
        ),
        migrations.RemoveField(
            model_name='snippets',
            name='lang',
        ),
    ]
