# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-16 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20180415_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippets',
            name='html',
            field=models.TextField(default='<html>'),
            preserve_default=False,
        ),
    ]
